<?php
return array(
	array(
		'field'   => 'name',
		'type'    => 'text',
		'name'    => 'name',
		'title'   => '配置标识',
		'note'    => '用于C函数调用，只能使用英文且不能重复',
		'extra'   => null,
		'is_show' => 3,
	),
	array(
		'field'   => 'title',
		'type'    => 'text',
		'name'    => 'title',
		'title'   => '配置标题',
		'note'    => '用于显示的配置标题',
		'extra'   => array(),
		'is_show' => 3,
	),
	array(
		'field'   => 'sort',
		'type'    => 'number',
		'name'    => 'sort',
		'title'   => '排序',
		'note'    => '用于分组显示的顺序',
		'extra'   => array(),
		'is_show' => 3,
		'value'   => 99,
	),
	array(
		'field'   => 'type',
		'type'    => 'select',
		'name'    => 'type',
		'title'   => '配置类型',
		'note'    => '系统会根据不同的类型解析配置值',
		'extra'   => get_form_type(),
		'is_show' => 3,
	),
	array(
		'field'   => 'group',
		'type'    => 'select',
		'name'    => 'group',
		'title'   => '配置分组',
		'note'    => '默认的是添加到默认分组',
		'extra'   => extra_to_array(C('CONFIG_GROUP')),
		'is_show' => 3,
	),
	array(
		'field'   => 'value',
		'name'    => 'value',
		'type'    => 'textarea',
		'title'   => '配置值',
		'note'    => '配置值',
		'extra'   => null,
		'is_show' => 3,
	),
	array(
		'field'   => 'extra',
		'name'    => 'extra',
		'type'    => 'textarea',
		'title'   => '配置项',
		'note'    => '如果是枚举值则要设置此项',
		'extra'   => null,
		'is_show' => 3,
	),
	array(
		'field'   => 'note',
		'name'    => 'note',
		'type'    => 'textarea',
		'title'   => '说明',
		'note'    => '配置详细说明',
		'extra'   => null,
		'is_show' => 3,
	),
	array(
		'field'   => 'no_del',
		'name'    => 'no_del',
		'type'    => 'radio',
		'title'   => '只有在开发模式下才能删除',
		'note'    => '关闭开发模式后此配置项不显示',
		'extra'   => array(
			0 => '否',
			1 => '是',
		),
		'is_show' => 3,
	),
	array(
		'field'   => 'is_show',
		'name'    => 'is_show',
		'type'    => 'radio',
		'title'   => '什么时候显示',
		'note'    => '关闭开发模式后在网站设置中是否显示',
		'extra'   => array(
			0 => '隐藏',
			1 => '添加时显示',
			2 => '编辑时显示',
			3 => '添加编辑时都显示',
		),
		'value'   => 3,
		'is_show' => 3,
	),
);